" use modern vim
set nocompatible
set encoding=utf-8

" use macbook delete as backspcace
set backspace=indent,eol,start 

" syntax highlighting
syntax enable

" 4 spaces indent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" visual stuff
set showcmd
set cursorline
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch

" hybrid line number
set number relativenumber

" fold
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

" fix mouse scrolling
set mouse=a

" keymap
let mapleader=","
nnoremap <space> za
nnoremap j gj
nnoremap k gk
nnoremap gV `[v`]
inoremap jk <esc>
nnoremap <leader>s :mksession<CR>
nnoremap <leader><space> :nohlsearch<CR>

" Filetype 
filetype plugin indent on
autocmd Filetype html setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd Filetype python setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType vim setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab